name: Test, Docker Build and Push
on:
  push:
    tags:
      - "*"
jobs:
  build-test-and-push-docker-container:
    name: Test, productionise, build container and push to Docker Hub
    runs-on: ubuntu-latest
    env:
      CI: true

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Initialize
        run: npm install && npm ci
      - name: Test
        run: npm run test -- --coverage
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            meezaan/realworld-ui:latest
            meezaan/realworld-ui:${{ github.ref_name }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Env Substring
        run: sudo apt-get update && sudo apt-get -y install gettext-base
      - name: Install Kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          chmod u+x ./kubectl
      - name: Deploy
        run: |
          curl -o ./.k8s/deploy.sh https://raw.githubusercontent.com/islamic-network/k8s-deployment/master/deploy.sh
          chmod u+x ./.k8s/deploy.sh
          export REF_NAME=${{ github.ref_name }}
          export K8S_URL=${{ secrets.K8S_URL }}
          export K8S_TOKEN=${{ secrets.K8S_TOKEN }}
          export K8S_CA=${{ secrets.K8S_CA }}
          sh ./.k8s/deploy.sh
